### ISSUE TITLE
Detailed and Summary 24-Hour Reports failing on empty counts

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#343]
**What Happened**
Some counts are "empty", in that they record no vehicles at all.  Detailed and Summary 24-Hour Reports fail to load on such counts.

**What Should Happen**
These reports should load successfully, and show that there are no counts.

**To Reproduce**
Steps to reproduce the bug:
1. Go to `view/location/1/14659630/reports/ATR_SPEED_VOLUME` in MOVE;
2. Click on '24-HOUR GRAPHICAL REPORT' or '24-HOUR SUMMARY REPORT' at top.

The report never loads; instead, the spinner continues spinning, and the backend issues an HTTP 500 error.

**Screenshots**
24-Hour Detailed Report failing to load:

![image](https://user-images.githubusercontent.com/151605/75699404-6a766480-5c7e-11ea-88e2-8adbae2fa368.png)

**Comment by candu** [comment]
To identify such a count:

```sql
-- find COUNT_INFO_ID values
select * from (select "COUNT_INFO_ID", sum("COUNT") as total from "TRAFFIC"."CNT_DET" group by "COUNT_INFO_ID") t where t.total = 0;

-- find count_group_id values
select * from counts.counts_multiday_runs where "COUNT_INFO_ID" = 1409307;

-- get centreline
select * from counts.studies where count_group_id = 1409307;

-- now visit /view/location/1/{centreline_id}/reports/ATR_SPEED_VOLUME
```

**Comment by candu** [comment]
Can't repro in latest MOVE on an empty speed / volume ATR - all 4 relevant report types seem to work here.  Closing as fixed.

**Comment by candu** [comment]
New repro courtesy of @aharpalaniTO : 24-hour detailed and summary reports fail at https://move.intra.dev-toronto.ca/view/location/1/1147135/reports/RESCU; this might be specific to particular study types?

**Comment by candu** [comment]
Stacktraces:

```
Debug: internal, implementation, error
    TypeError: Cannot read property 't' of undefined
    at Function.transformCountData (/home/ec2-user/flashcrow/lib/reports/ReportCountSummary24hDetailed.js:21:36)
    at /home/ec2-user/flashcrow/lib/reports/ReportCountSummary24hDetailed.js:44:60
    at Array.map (<anonymous>)
    at ReportCountSummary24hDetailed.transformData (/home/ec2-user/flashcrow/lib/reports/ReportCountSummary24hDetailed.js:38:19)
    at ReportCountSummary24hDetailed.generate (/home/ec2-user/flashcrow/lib/reports/ReportBase.js:122:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handler (/home/ec2-user/flashcrow/lib/controller/ReportController.js:106:26)
    at async exports.Manager.execute (/home/ec2-user/flashcrow/node_modules/@hapi/hapi/lib/toolkit.js:64:28)
    at async Object.internals.handler (/home/ec2-user/flashcrow/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at async exports.execute (/home/ec2-user/flashcrow/node_modules/@hapi/hapi/lib/handler.js:31:20)
```

```
Debug: internal, implementation, error
    TypeError: Cannot read property 't' of undefined
    at Function.timeRange (/home/ec2-user/flashcrow/lib/reports/ReportCountSummary24h.js:52:36)
    at Function.peakSection (/home/ec2-user/flashcrow/lib/reports/ReportCountSummary24h.js:85:45)
    at transformCountData (/home/ec2-user/flashcrow/lib/reports/ReportCountSummary24h.js:116:42)
    at Array.map (<anonymous>)
    at /home/ec2-user/flashcrow/lib/reports/ReportCountSummary24h.js:188:35
    at Array.forEach (<anonymous>)
    at ReportCountSummary24h.transformData (/home/ec2-user/flashcrow/lib/reports/ReportCountSummary24h.js:176:34)
    at ReportCountSummary24h.generate (/home/ec2-user/flashcrow/lib/reports/ReportBase.js:122:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handler (/home/ec2-user/flashcrow/lib/controller/ReportController.js:106:26)
```
